### GlobalManager
### Manager to handle current general data
extends Node

var currentPlayer: Player
var bossCounter: int = 4
var currentEnemyId: String
var currentMap: GameEnums.MapEnum = GameEnums.MapEnum.MAP1
var currentMapVal: int = 0
var playerDefaultPosision: Vector2 = Vector2(400, 400)
var playerPosisionBeforeLastBattle: Vector2 = playerDefaultPosision
var bossKilled: bool = false;
const DAMAGE: int = 5
const defaultQuestions: Dictionary = {}
var gameQuestions: Dictionary = defaultQuestions
var mathQuestions := [
	{"question": "Quanto é 7 + 5?", "isBoss": false, "answers": [ {"answer": "10", "correct": false}, {"answer": "12", "correct": true}, {"answer": "13", "correct": false}, {"answer": "14", "correct": false}]},
	{"question": "Qual é o resultado de 9 × 3?", "isBoss": false, "answers": [ {"answer": "27", "correct": true}, {"answer": "26", "correct": false}, {"answer": "29", "correct": false}, {"answer": "30", "correct": false}]},
	{"question": "Quanto é 45 ÷ 5?", "isBoss": false, "answers": [ {"answer": "8", "correct": false}, {"answer": "9", "correct": true}, {"answer": "10", "correct": false}, {"answer": "11", "correct": false}]},
	{"question": "Qual é a fração equivalente a 2/4?", "isBoss": false, "answers": [ {"answer": "1/2", "correct": true}, {"answer": "2/3", "correct": false}, {"answer": "3/4", "correct": false}, {"answer": "1/4", "correct": false}]},
	{"question": "Quanto é 15 - 7?", "isBoss": false, "answers": [ {"answer": "7", "correct": false}, {"answer": "8", "correct": true}, {"answer": "9", "correct": false}, {"answer": "10", "correct": false}]},
	{"question": "Qual é o resultado de 8 × 6?", "isBoss": true, "answers": [ {"answer": "42", "correct": false}, {"answer": "48", "correct": true}, {"answer": "46", "correct": false}, {"answer": "54", "correct": false}]},
	{"question": "Quanto é 56 ÷ 8?", "isBoss": false, "answers": [ {"answer": "6", "correct": false}, {"answer": "7", "correct": true}, {"answer": "8", "correct": false}, {"answer": "9", "correct": false}]},
	{"question": "Qual número completa a sequência: 2, 4, 6, ?", "isBoss": false, "answers": [ {"answer": "8", "correct": true}, {"answer": "7", "correct": false}, {"answer": "9", "correct": false}, {"answer": "6", "correct": false}]},
	{"question": "Quanto é 100 - 37?", "isBoss": false, "answers": [ {"answer": "63", "correct": true}, {"answer": "67", "correct": false}, {"answer": "64", "correct": false}, {"answer": "62", "correct": false}]},
	{"question": "Qual é o resultado de 12 × 4?", "isBoss": false, "answers": [ {"answer": "48", "correct": true}, {"answer": "44", "correct": false}, {"answer": "52", "correct": false}, {"answer": "42", "correct": false}]},
	{"question": "Qual é 3/5 + 1/5?", "isBoss": true, "answers": [ {"answer": "4/5", "correct": true}, {"answer": "3/10", "correct": false}, {"answer": "1/5", "correct": false}, {"answer": "5/5", "correct": false}]},
	{"question": "Quanto é 14 ÷ 2?", "isBoss": false, "answers": [ {"answer": "6", "correct": false}, {"answer": "7", "correct": true}, {"answer": "8", "correct": false}, {"answer": "9", "correct": false}]},
	{"question": "Se um lápis custa R$3, quanto custam 5 lápis?", "isBoss": false, "answers": [ {"answer": "15", "correct": true}, {"answer": "10", "correct": false}, {"answer": "12", "correct": false}, {"answer": "13", "correct": false}]},
	{"question": "Qual número é maior: 3/4 ou 5/8?", "isBoss": false, "answers": [ {"answer": "3/4", "correct": true}, {"answer": "5/8", "correct": false}, {"answer": "iguais", "correct": false}, {"answer": "não dá para saber", "correct": false}]},
	{"question": "Quanto é 9 + 8?", "isBoss": false, "answers": [ {"answer": "17", "correct": true}, {"answer": "16", "correct": false}, {"answer": "18", "correct": false}, {"answer": "19", "correct": false}]},
	{"question": "Quanto é 7 × 7?", "isBoss": false, "answers": [ {"answer": "49", "correct": true}, {"answer": "42", "correct": false}, {"answer": "56", "correct": false}, {"answer": "48", "correct": false}]},
	{"question": "Quanto é 64 ÷ 8?", "isBoss": false, "answers": [ {"answer": "6", "correct": false}, {"answer": "8", "correct": true}, {"answer": "7", "correct": false}, {"answer": "9", "correct": false}]},
	{"question": "Qual número completa a sequência: 5, 10, 15, ?", "isBoss": false, "answers": [ {"answer": "20", "correct": true}, {"answer": "25", "correct": false}, {"answer": "18", "correct": false}, {"answer": "15", "correct": false}]},
	{"question": "Quanto é 50 - 23?", "isBoss": false, "answers": [ {"answer": "27", "correct": true}, {"answer": "28", "correct": false}, {"answer": "26", "correct": false}, {"answer": "25", "correct": false}]},
	{"question": "Qual é o resultado de 11 × 5?", "isBoss": false, "answers": [ {"answer": "55", "correct": true}, {"answer": "50", "correct": false}, {"answer": "60", "correct": false}, {"answer": "54", "correct": false}]},
	{"question": "Quanto é 1/2 + 1/3?", "isBoss": true, "answers": [ {"answer": "5/6", "correct": true}, {"answer": "2/5", "correct": false}, {"answer": "1/5", "correct": false}, {"answer": "3/4", "correct": false}]},
	{"question": "Quanto é 36 ÷ 6?", "isBoss": false, "answers": [ {"answer": "6", "correct": true}, {"answer": "7", "correct": false}, {"answer": "5", "correct": false}, {"answer": "8", "correct": false}]},
	{"question": "Qual é o dobro de 18?", "isBoss": false, "answers": [ {"answer": "36", "correct": true}, {"answer": "34", "correct": false}, {"answer": "38", "correct": false}, {"answer": "32", "correct": false}]},
	{"question": "Quanto é 100 ÷ 4?", "isBoss": false, "answers": [ {"answer": "25", "correct": true}, {"answer": "20", "correct": false}, {"answer": "30", "correct": false}, {"answer": "24", "correct": false}]},
	{"question": "Qual é o resultado de 6 × 9?", "isBoss": false, "answers": [ {"answer": "54", "correct": true}, {"answer": "56", "correct": false}, {"answer": "48", "correct": false}, {"answer": "52", "correct": false}]},
	{"question": "Quanto é 13 + 14?", "isBoss": false, "answers": [ {"answer": "27", "correct": true}, {"answer": "26", "correct": false}, {"answer": "28", "correct": false}, {"answer": "25", "correct": false}]},
	{"question": "Qual é a fração equivalente a 4/8?", "isBoss": false, "answers": [ {"answer": "1/2", "correct": true}, {"answer": "2/3", "correct": false}, {"answer": "3/4", "correct": false}, {"answer": "1/4", "correct": false}]},
	{"question": "Quanto é 18 ÷ 3?", "isBoss": false, "answers": [ {"answer": "5", "correct": false}, {"answer": "6", "correct": true}, {"answer": "7", "correct": false}, {"answer": "8", "correct": false}]},
	{"question": "Qual número completa a sequência: 10, 20, 30, ?", "isBoss": false, "answers": [ {"answer": "40", "correct": true}, {"answer": "50", "correct": false}, {"answer": "35", "correct": false}, {"answer": "45", "correct": false}]},
	{"question": "Quanto é 72 - 28?", "isBoss": false, "answers": [ {"answer": "44", "correct": true}, {"answer": "45", "correct": false}, {"answer": "43", "correct": false}, {"answer": "46", "correct": false}]},
	{"question": "Qual é o resultado de 8 × 8?", "isBoss": true, "answers": [ {"answer": "64", "correct": true}, {"answer": "60", "correct": false}, {"answer": "66", "correct": false}, {"answer": "68", "correct": false}]},
	{"question": "Quanto é 5/6 - 1/6?", "isBoss": true, "answers": [ {"answer": "4/6", "correct": true}, {"answer": "3/6", "correct": false}, {"answer": "2/6", "correct": false}, {"answer": "5/6", "correct": false}]},
	{"question": "Quanto é 81 ÷ 9?", "isBoss": false, "answers": [ {"answer": "9", "correct": true}, {"answer": "8", "correct": false}, {"answer": "10", "correct": false}, {"answer": "7", "correct": false}]},
	{"question": "Se um livro custa R$12, quanto custam 4 livros?", "isBoss": false, "answers": [ {"answer": "48", "correct": true}, {"answer": "36", "correct": false}, {"answer": "40", "correct": false}, {"answer": "44", "correct": false}]},
	{"question": "Quanto é 15 × 3?", "isBoss": false, "answers": [ {"answer": "45", "correct": true}, {"answer": "40", "correct": false}, {"answer": "50", "correct": false}, {"answer": "42", "correct": false}]},
	{"question": "Qual número é maior: 7/8 ou 3/4?", "isBoss": false, "answers": [ {"answer": "7/8", "correct": true}, {"answer": "3/4", "correct": false}, {"answer": "iguais", "correct": false}, {"answer": "não dá para saber", "correct": false}]},
	{"question": "Quanto é 19 + 21?", "isBoss": false, "answers": [ {"answer": "40", "correct": true}, {"answer": "41", "correct": false}, {"answer": "39", "correct": false}, {"answer": "42", "correct": false}]},
	{"question": "Quanto é 9 × 12?", "isBoss": true, "answers": [ {"answer": "108", "correct": true}, {"answer": "112", "correct": false}, {"answer": "102", "correct": false}, {"answer": "110", "correct": false}]},
	{"question": "Quanto é 56 ÷ 7?", "isBoss": false, "answers": [ {"answer": "8", "correct": true}, {"answer": "7", "correct": false}, {"answer": "6", "correct": false}, {"answer": "9", "correct": false}]},
	{"question": "Qual número completa a sequência: 1, 4, 7, 10, ?", "isBoss": false, "answers": [ {"answer": "13", "correct": true}, {"answer": "12", "correct": false}, {"answer": "14", "correct": false}, {"answer": "15", "correct": false}]},
	{"question": "Quanto é 65 - 29?", "isBoss": false, "answers": [ {"answer": "36", "correct": true}, {"answer": "35", "correct": false}, {"answer": "37", "correct": false}, {"answer": "34", "correct": false}]},
	{"question": "Quanto é 14 × 6?", "isBoss": false, "answers": [ {"answer": "84", "correct": true}, {"answer": "80", "correct": false}, {"answer": "78", "correct": false}, {"answer": "86", "correct": false}]},
	{"question": "Quanto é 7/10 + 2/10?", "isBoss": false, "answers": [ {"answer": "9/10", "correct": true}, {"answer": "8/10", "correct": false}, {"answer": "10/10", "correct": false}, {"answer": "7/10", "correct": false}]},
	{"question": "Quanto é 90 ÷ 10?", "isBoss": false, "answers": [ {"answer": "9", "correct": true}, {"answer": "10", "correct": false}, {"answer": "8", "correct": false}, {"answer": "11", "correct": false}]},
	{"question": "Qual é o triplo de 13?", "isBoss": false, "answers": [ {"answer": "39", "correct": true}, {"answer": "36", "correct": false}, {"answer": "33", "correct": false}, {"answer": "42", "correct": false}]},
	{"question": "Quanto é 120 ÷ 12?", "isBoss": false, "answers": [ {"answer": "10", "correct": true}, {"answer": "12", "correct": false}, {"answer": "8", "correct": false}, {"answer": "9", "correct": false}]},
	{"question": "Quanto é 8 × 11?", "isBoss": false, "answers": [ {"answer": "88", "correct": true}, {"answer": "81", "correct": false}, {"answer": "84", "correct": false}, {"answer": "86", "correct": false}]},
	{"question": "Quanto é 25 + 17?", "isBoss": false, "answers": [ {"answer": "42", "correct": true}, {"answer": "41", "correct": false}, {"answer": "43", "correct": false}, {"answer": "40", "correct": false}]},
	{"question": "Qual é a fração equivalente a 6/12?", "isBoss": false, "answers": [ {"answer": "1/2", "correct": true}, {"answer": "2/3", "correct": false}, {"answer": "3/4", "correct": false}, {"answer": "1/3", "correct": false}]},
	{"question": "Quanto é 21 ÷ 7?", "isBoss": false, "answers": [ {"answer": "3", "correct": true}, {"answer": "2", "correct": false}, {"answer": "4", "correct": false}, {"answer": "5", "correct": false}]},
	{"question": "Qual número completa a sequência: 3, 6, 9, 12, ?", "isBoss": false, "answers": [ {"answer": "15", "correct": true}, {"answer": "14", "correct": false}, {"answer": "16", "correct": false}, {"answer": "18", "correct": false}]},
	{"question": "Quanto é 48 - 19?", "isBoss": false, "answers": [ {"answer": "29", "correct": true}, {"answer": "28", "correct": false}, {"answer": "30", "correct": false}, {"answer": "27", "correct": false}]}
]
var portugueseQuestions := [
	{"question": "Qual palavra está escrita corretamente?", "isBoss": false, "answers": [ {"answer": "Excessão", "correct": false}, {"answer": "Exceção", "correct": true}, {"answer": "Exceçāo", "correct": false}, {"answer": "Excesão", "correct": false}]},
	{"question": "Qual a forma correta do plural de 'coração'?", "isBoss": false, "answers": [ {"answer": "Corações", "correct": true}, {"answer": "Coraçōes", "correct": false}, {"answer": "Coraçoes", "correct": false}, {"answer": "Coraçães", "correct": false}]},
	{"question": "Assinale a frase com pontuação correta.", "isBoss": false, "answers": [ {"answer": "Vamos, ao parque hoje.", "correct": false}, {"answer": "Vamos ao parque hoje.", "correct": true}, {"answer": "Vamos ao parque, hoje", "correct": false}, {"answer": "Vamos ao parque hoje,", "correct": false}]},
	{"question": "Qual é o substantivo na frase: 'O gato dormiu no sofá'?", "isBoss": false, "answers": [ {"answer": "dormiu", "correct": false}, {"answer": "gato", "correct": true}, {"answer": "no", "correct": false}, {"answer": "sofá", "correct": false}]},
	{"question": "Qual é o adjetivo na frase: 'A casa grande é bonita'?", "isBoss": false, "answers": [ {"answer": "casa", "correct": false}, {"answer": "grande", "correct": true}, {"answer": "bonita", "correct": false}, {"answer": "é", "correct": false}]},
	{"question": "Escolha a palavra com a sílaba tônica correta.", "isBoss": true, "answers": [ {"answer": "Lâmpada", "correct": true}, {"answer": "Lampada", "correct": false}, {"answer": "Lãmpada", "correct": false}, {"answer": "Lampadá", "correct": false}]},
	{"question": "Qual das palavras é um verbo?", "isBoss": false, "answers": [ {"answer": "Correr", "correct": true}, {"answer": "Rápido", "correct": false}, {"answer": "Casa", "correct": false}, {"answer": "Bonito", "correct": false}]},
	{"question": "Qual é a forma correta: 'mais melhor' ou 'melhor'?", "isBoss": false, "answers": [ {"answer": "mais melhor", "correct": false}, {"answer": "melhor", "correct": true}, {"answer": "melhór", "correct": false}, {"answer": "mai melhor", "correct": false}]},
	{"question": "Escolha a frase correta.", "isBoss": false, "answers": [ {"answer": "Eu vôu à escola.", "correct": false}, {"answer": "Eu vou à escola.", "correct": true}, {"answer": "Eu vou a escola", "correct": false}, {"answer": "Eu vou à escola!", "correct": false}]},
	{"question": "Assinale a frase com a conjugação correta do verbo 'fazer'.", "isBoss": false, "answers": [ {"answer": "Ela faz os deveres.", "correct": true}, {"answer": "Ela faze os deveres.", "correct": false}, {"answer": "Ela fazo os deveres.", "correct": false}, {"answer": "Ela fazê os deveres.", "correct": false}]},
	{"question": "Qual palavra tem 's' com som de 'z'?", "isBoss": true, "answers": [ {"answer": "Cesar", "correct": true}, {"answer": "Sapo", "correct": false}, {"answer": "Saco", "correct": false}, {"answer": "Sede", "correct": false}]},
	{"question": "Qual é a forma correta do plural: 'lápis'?", "isBoss": false, "answers": [ {"answer": "Lápis", "correct": true}, {"answer": "Lápises", "correct": false}, {"answer": "Lápisês", "correct": false}, {"answer": "Lapises", "correct": false}]},
	{"question": "Assinale a frase com erro de ortografia.", "isBoss": false, "answers": [ {"answer": "O menino brincou no quintal.", "correct": false}, {"answer": "Eu gostei do livro.", "correct": false}, {"answer": "Ela comprou uma blusa azul.", "correct": false}, {"answer": "Eu vái à escola.", "correct": true}]},
	{"question": "Escolha a frase com acento correto.", "isBoss": false, "answers": [ {"answer": "Ele está feliz.", "correct": true}, {"answer": "Ele esta feliz", "correct": false}, {"answer": "Ele estâ feliz", "correct": false}, {"answer": "Ele está feliz!", "correct": false}]},
	{"question": "Qual palavra é um advérbio de tempo?", "isBoss": false, "answers": [ {"answer": "Ontem", "correct": true}, {"answer": "Bonito", "correct": false}, {"answer": "Correr", "correct": false}, {"answer": "Casa", "correct": false}]},
	{"question": "Qual é a forma correta: 'A gente vai' ou 'A gente vamos'?", "isBoss": false, "answers": [ {"answer": "A gente vamos", "correct": false}, {"answer": "A gente vai", "correct": true}, {"answer": "A gente vão", "correct": false}, {"answer": "A gente vaii", "correct": false}]},
	{"question": "Qual das palavras é um pronome pessoal?", "isBoss": true, "answers": [ {"answer": "Ela", "correct": true}, {"answer": "Gato", "correct": false}, {"answer": "Bonito", "correct": false}, {"answer": "Casa", "correct": false}]},
	{"question": "Escolha a frase com vírgula correta.", "isBoss": false, "answers": [ {"answer": "Pedro, foi ao mercado.", "correct": false}, {"answer": "Pedro foi ao mercado.", "correct": true}, {"answer": "Pedro foi, ao mercado.", "correct": false}, {"answer": "Pedro foi ao, mercado.", "correct": false}]},
	{"question": "Qual palavra é um substantivo comum?", "isBoss": false, "answers": [ {"answer": "Cachorro", "correct": true}, {"answer": "Feliz", "correct": false}, {"answer": "Correr", "correct": false}, {"answer": "Bonito", "correct": false}]},
	{"question": "Qual é a forma correta do plural: 'cidadão'?", "isBoss": false, "answers": [ {"answer": "Cidadãos", "correct": true}, {"answer": "Cidadãoses", "correct": false}, {"answer": "Cidadãoes", "correct": false}, {"answer": "Cidadães", "correct": false}]},
	{"question": "Assinale a palavra com acento correto.", "isBoss": true, "answers": [ {"answer": "Pôde", "correct": true}, {"answer": "Pode", "correct": false}, {"answer": "Pôdê", "correct": false}, {"answer": "Póde", "correct": false}]},
	{"question": "Qual é o plural de 'barril'?", "isBoss": false, "answers": [ {"answer": "Barris", "correct": true}, {"answer": "Barris", "correct": false}, {"answer": "Barrils", "correct": false}, {"answer": "Barríis", "correct": false}]},
	{"question": "Escolha a palavra com ortografia correta.", "isBoss": false, "answers": [ {"answer": "Haviam", "correct": false}, {"answer": "Havia", "correct": true}, {"answer": "Haviám", "correct": false}, {"answer": "Havía", "correct": false}]},
	{"question": "Qual é a forma correta: 'para mim' ou 'para eu'?", "isBoss": false, "answers": [ {"answer": "Para mim", "correct": true}, {"answer": "Para eu", "correct": false}, {"answer": "Para mi", "correct": false}, {"answer": "Para mimme", "correct": false}]},
	{"question": "Assinale a frase com erro de concordância.", "isBoss": false, "answers": [ {"answer": "Os meninos jogaram bola.", "correct": false}, {"answer": "As meninas cantaram.", "correct": false}, {"answer": "A gente vamos estudar.", "correct": true}, {"answer": "O cachorro dormiu.", "correct": false}]},
	{"question": "Qual palavra é um adjetivo?", "isBoss": true, "answers": [ {"answer": "Bonito", "correct": true}, {"answer": "Correr", "correct": false}, {"answer": "Casa", "correct": false}, {"answer": "Ele", "correct": false}]},
	{"question": "Qual é o antônimo de 'alto'?", "isBoss": false, "answers": [ {"answer": "Baixo", "correct": true}, {"answer": "Grande", "correct": false}, {"answer": "Pequeno", "correct": false}, {"answer": "Longo", "correct": false}]},
	{"question": "Qual é a forma correta de 'mal' ou 'mau'?", "isBoss": false, "answers": [ {"answer": "Mau amigo", "correct": true}, {"answer": "Mal amigo", "correct": false}, {"answer": "Mau", "correct": false}, {"answer": "Mâl", "correct": false}]},
	{"question": "Assinale a frase correta.", "isBoss": false, "answers": [ {"answer": "Nós vamos à festa.", "correct": true}, {"answer": "Nos vamos à festa.", "correct": false}, {"answer": "Nós vamos a festa", "correct": false}, {"answer": "Nos vamos a festa.", "correct": false}]},
	{"question": "Qual é o sujeito da frase: 'O cachorro latiu'?", "isBoss": false, "answers": [ {"answer": "O cachorro", "correct": true}, {"answer": "latiu", "correct": false}, {"answer": "O", "correct": false}, {"answer": "Cachorro latiu", "correct": false}]},
	{"question": "Escolha a palavra correta: 'sessão, seção ou cesão'?", "isBoss": true, "answers": [ {"answer": "Seção", "correct": true}, {"answer": "Sessão", "correct": false}, {"answer": "Cesão", "correct": false}, {"answer": "Secção", "correct": false}]},
	{"question": "Qual é a forma correta: 'por que', 'porque', 'porquê' ou 'por quê'?", "isBoss": false, "answers": [ {"answer": "Porque", "correct": true}, {"answer": "Por que", "correct": false}, {"answer": "Porquê", "correct": false}, {"answer": "Por quê", "correct": false}]},
	{"question": "Qual é a forma correta de escrever: 'pôde' ou 'pode'?", "isBoss": false, "answers": [ {"answer": "Pôde", "correct": true}, {"answer": "Pode", "correct": false}, {"answer": "Podê", "correct": false}, {"answer": "Podé", "correct": false}]},
	{"question": "Assinale a palavra com sílaba tônica correta.", "isBoss": false, "answers": [ {"answer": "Árvore", "correct": true}, {"answer": "Arvore", "correct": false}, {"answer": "Árvoore", "correct": false}, {"answer": "Arvóre", "correct": false}]},
	{"question": "Qual palavra está escrita corretamente?", "isBoss": false, "answers": [ {"answer": "Recêber", "correct": false}, {"answer": "Receber", "correct": true}, {"answer": "Recebêr", "correct": false}, {"answer": "Resséber", "correct": false}]},
	{"question": "Qual é o plural de 'fóssil'?", "isBoss": false, "answers": [ {"answer": "Fósseis", "correct": true}, {"answer": "Fossis", "correct": false}, {"answer": "Fóssils", "correct": false}, {"answer": "Fósséis", "correct": false}]},
	{"question": "Qual é a forma correta de 'há' ou 'a'?", "isBoss": true, "answers": [ {"answer": "Há dois anos", "correct": true}, {"answer": "A dois anos", "correct": false}, {"answer": "Há dois anos atrás", "correct": false}, {"answer": "A dois anos atrás", "correct": false}]},
	{"question": "Qual palavra é um substantivo próprio?", "isBoss": false, "answers": [ {"answer": "Vinicius", "correct": true}, {"answer": "Cachorro", "correct": false}, {"answer": "Bonito", "correct": false}, {"answer": "Casa", "correct": false}]},
	{"question": "Assinale a frase com pontuação correta.", "isBoss": false, "answers": [ {"answer": "João, Maria e Pedro foram ao parque.", "correct": true}, {"answer": "João Maria e Pedro foram ao parque.", "correct": false}, {"answer": "João Maria, e Pedro foram ao parque", "correct": false}, {"answer": "João, Maria, e Pedro foram ao parque", "correct": false}]},
	{"question": "Qual palavra é um advérbio de intensidade?", "isBoss": true, "answers": [ {"answer": "Muito", "correct": true}, {"answer": "Bonito", "correct": false}, {"answer": "Correr", "correct": false}, {"answer": "Casa", "correct": false}]},
	{"question": "Escolha a forma correta: 'mais' ou 'mas'?", "isBoss": false, "answers": [ {"answer": "Mas eu não sei.", "correct": true}, {"answer": "Mais eu não sei", "correct": false}, {"answer": "Mas eu não sei!", "correct": false}, {"answer": "Mais eu não sei!", "correct": false}]},
	{"question": "Qual é o plural de 'animal'?", "isBoss": false, "answers": [ {"answer": "Animais", "correct": true}, {"answer": "Animalis", "correct": false}, {"answer": "Animáis", "correct": false}, {"answer": "Animai", "correct": false}]},
	{"question": "Qual é a forma correta: 'têm' ou 'tem'?", "isBoss": false, "answers": [ {"answer": "Eles têm amigos", "correct": true}, {"answer": "Eles tem amigos", "correct": false}, {"answer": "Eles têm amigos?", "correct": false}, {"answer": "Eles tem amigos?", "correct": false}]},
	{"question": "Qual é a forma correta de 'por que' ou 'porque'?", "isBoss": false, "answers": [ {"answer": "Porque ele não veio", "correct": true}, {"answer": "Por que ele não veio", "correct": false}, {"answer": "Porquê ele não veio", "correct": false}, {"answer": "Por quê ele não veio", "correct": false}]}
]
var cienceQuestions := [
	{"question": "Qual é a principal função das raízes nas plantas?", "isBoss": false, "answers": [ {"answer": "Produzir flores", "correct": false}, {"answer": "Absorver água e nutrientes", "correct": true}, {"answer": "Fotossintetizar", "correct": false}, {"answer": "Armazenar sementes", "correct": false}]},
	{"question": "Qual planeta é conhecido como Planeta Vermelho?", "isBoss": false, "answers": [ {"answer": "Marte", "correct": true}, {"answer": "Vênus", "correct": false}, {"answer": "Júpiter", "correct": false}, {"answer": "Saturno", "correct": false}]},
	{"question": "Qual é a fonte primária de energia para os seres vivos?", "isBoss": false, "answers": [ {"answer": "Água", "correct": false}, {"answer": "Luz solar", "correct": true}, {"answer": "Ar", "correct": false}, {"answer": "Solo", "correct": false}]},
	{"question": "O que o corpo humano produz para defender-se de doenças?", "isBoss": false, "answers": [ {"answer": "Vitaminas", "correct": false}, {"answer": "Anticorpos", "correct": true}, {"answer": "Gordura", "correct": false}, {"answer": "Carboidratos", "correct": false}]},
	{"question": "Qual é a função do coração no corpo humano?", "isBoss": false, "answers": [ {"answer": "Filtrar sangue", "correct": false}, {"answer": "Bombear sangue", "correct": true}, {"answer": "Produzir hormônios", "correct": false}, {"answer": "Controlar respiração", "correct": false}]},
	{"question": "Qual fenômeno faz a água passar do estado líquido para gasoso?", "isBoss": true, "answers": [ {"answer": "Evaporação", "correct": true}, {"answer": "Condensação", "correct": false}, {"answer": "Congelação", "correct": false}, {"answer": "Sublimação", "correct": false}]},
	{"question": "Qual órgão é responsável pela digestão dos alimentos?", "isBoss": false, "answers": [ {"answer": "Estômago", "correct": true}, {"answer": "Coração", "correct": false}, {"answer": "Pulmão", "correct": false}, {"answer": "Rim", "correct": false}]},
	{"question": "O que é fotossíntese?", "isBoss": false, "answers": [ {"answer": "Processo das plantas produzirem alimento usando luz solar", "correct": true}, {"answer": "Respiração dos animais", "correct": false}, {"answer": "Movimento da água", "correct": false}, {"answer": "Decomposição de matéria orgânica", "correct": false}]},
	{"question": "Qual é o gás mais abundante na atmosfera terrestre?", "isBoss": false, "answers": [ {"answer": "Nitrogênio", "correct": true}, {"answer": "Oxigênio", "correct": false}, {"answer": "Dióxido de carbono", "correct": false}, {"answer": "Hélio", "correct": false}]},
	{"question": "Qual é a camada da Terra onde vivemos?", "isBoss": false, "answers": [ {"answer": "Crosta", "correct": true}, {"answer": "Manto", "correct": false}, {"answer": "Núcleo", "correct": false}, {"answer": "Litosfera", "correct": false}]},
	{"question": "Qual é a principal função das folhas nas plantas?", "isBoss": true, "answers": [ {"answer": "Realizar fotossíntese", "correct": true}, {"answer": "Absorver água", "correct": false}, {"answer": "Produzir sementes", "correct": false}, {"answer": "Armazenar nutrientes", "correct": false}]},
	{"question": "O que é um ecossistema?", "isBoss": false, "answers": [ {"answer": "Um conjunto de organismos e o ambiente em que vivem", "correct": true}, {"answer": "Um tipo de solo", "correct": false}, {"answer": "Um planeta", "correct": false}, {"answer": "Um animal raro", "correct": false}]},
	{"question": "O que os vírus necessitam para se reproduzir?", "isBoss": false, "answers": [ {"answer": "Células de outros seres vivos", "correct": true}, {"answer": "Água pura", "correct": false}, {"answer": "Ar", "correct": false}, {"answer": "Solo fértil", "correct": false}]},
	{"question": "Qual é a função dos pulmões?", "isBoss": false, "answers": [ {"answer": "Trocar gases com o sangue", "correct": true}, {"answer": "Bombear sangue", "correct": false}, {"answer": "Produzir hormônios", "correct": false}, {"answer": "Filtrar líquidos", "correct": false}]},
	{"question": "Qual é a maior camada da Terra?", "isBoss": false, "answers": [ {"answer": "Manto", "correct": true}, {"answer": "Crosta", "correct": false}, {"answer": "Núcleo", "correct": false}, {"answer": "Litosfera", "correct": false}]},
	{"question": "Qual é a unidade básica da vida?", "isBoss": true, "answers": [ {"answer": "Célula", "correct": true}, {"answer": "Átomo", "correct": false}, {"answer": "Molécula", "correct": false}, {"answer": "Tecido", "correct": false}]},
	{"question": "O que é a camada de ozônio responsável?", "isBoss": false, "answers": [ {"answer": "Proteger a Terra da radiação ultravioleta", "correct": true}, {"answer": "Produzir oxigênio", "correct": false}, {"answer": "Absorver dióxido de carbono", "correct": false}, {"answer": "Regular a temperatura da Terra", "correct": false}]},
	{"question": "Qual é a principal fonte de energia para o planeta?", "isBoss": false, "answers": [ {"answer": "Sol", "correct": true}, {"answer": "Vento", "correct": false}, {"answer": "Água", "correct": false}, {"answer": "Carvão", "correct": false}]},
	{"question": "O que é reciclagem?", "isBoss": false, "answers": [ {"answer": "Processo de reaproveitar materiais usados", "correct": true}, {"answer": "Queimar lixo", "correct": false}, {"answer": "Descartar lixo na rua", "correct": false}, {"answer": "Produzir novos produtos sem usar materiais antigos", "correct": false}]},
	{"question": "Quem descobriu o Brasil?", "isBoss": true, "answers": [ {"answer": "Pedro Álvares Cabral", "correct": true}, {"answer": "Cristóvão Colombo", "correct": false}, {"answer": "Vasco da Gama", "correct": false}, {"answer": "Fernão de Magalhães", "correct": false}]},
	{"question": "Qual é a capital do Brasil?", "isBoss": false, "answers": [ {"answer": "Brasília", "correct": true}, {"answer": "Rio de Janeiro", "correct": false}, {"answer": "São Paulo", "correct": false}, {"answer": "Salvador", "correct": false}]},
	{"question": "O que é energia renovável?", "isBoss": false, "answers": [ {"answer": "Energia obtida de fontes que se renovam naturalmente", "correct": true}, {"answer": "Energia elétrica", "correct": false}, {"answer": "Energia nuclear", "correct": false}, {"answer": "Energia dos combustíveis fósseis", "correct": false}]},
	{"question": "Quem foi o primeiro presidente do Brasil?", "isBoss": false, "answers": [ {"answer": "Deodoro da Fonseca", "correct": true}, {"answer": "Getúlio Vargas", "correct": false}, {"answer": "Juscelino Kubitschek", "correct": false}, {"answer": "Floriano Peixoto", "correct": false}]},
	{"question": "O que é um continente?", "isBoss": false, "answers": [ {"answer": "Uma grande extensão de terra", "correct": true}, {"answer": "Uma ilha pequena", "correct": false}, {"answer": "Um país", "correct": false}, {"answer": "Um oceano", "correct": false}]},
	{"question": "Qual é a camada mais externa da Terra?", "isBoss": false, "answers": [ {"answer": "Crosta", "correct": true}, {"answer": "Manto", "correct": false}, {"answer": "Núcleo", "correct": false}, {"answer": "Litosfera", "correct": false}]},
	{"question": "O que os fósseis indicam?", "isBoss": false, "answers": [ {"answer": "Espécies que viveram no passado", "correct": true}, {"answer": "Espécies que existem hoje", "correct": false}, {"answer": "Recursos naturais", "correct": false}, {"answer": "Plantas atuais", "correct": false}]},
	{"question": "O que é terremoto?", "isBoss": true, "answers": [ {"answer": "Movimento súbito da Terra causado por placas tectônicas", "correct": true}, {"answer": "Tempestade com chuva", "correct": false}, {"answer": "Explosão de vulcão", "correct": false}, {"answer": "Ondas do mar", "correct": false}]},
	{"question": "Qual é o estado físico da água em um lago congelado?", "isBoss": false, "answers": [ {"answer": "Sólido", "correct": true}, {"answer": "Líquido", "correct": false}, {"answer": "Gasoso", "correct": false}, {"answer": "Plasma", "correct": false}]},
	{"question": "O que os músculos fazem no corpo humano?", "isBoss": false, "answers": [ {"answer": "Movem partes do corpo", "correct": true}, {"answer": "Transportam sangue", "correct": false}, {"answer": "Produzem hormônios", "correct": false}, {"answer": "Filtram líquidos", "correct": false}]},
	{"question": "Qual é o principal gás que respiramos?", "isBoss": false, "answers": [ {"answer": "Oxigênio", "correct": true}, {"answer": "Nitrogênio", "correct": false}, {"answer": "Dióxido de carbono", "correct": false}, {"answer": "Hidrogênio", "correct": false}]},
	{"question": "O que é poluição do ar?", "isBoss": false, "answers": [ {"answer": "Contaminação da atmosfera por gases e partículas", "correct": true}, {"answer": "Lixo jogado no chão", "correct": false}, {"answer": "Erosão do solo", "correct": false}, {"answer": "Desmatamento", "correct": false}]},
	{"question": "Qual é a principal função do cérebro?", "isBoss": true, "answers": [ {"answer": "Controlar o corpo e as funções cognitivas", "correct": true}, {"answer": "Bombear sangue", "correct": false}, {"answer": "Produzir hormônios", "correct": false}, {"answer": "Filtrar sangue", "correct": false}]},
	{"question": "Qual era a capital do Império Romano?", "isBoss": false, "answers": [ {"answer": "Roma", "correct": true}, {"answer": "Atenas", "correct": false}, {"answer": "Cartago", "correct": false}, {"answer": "Bizâncio", "correct": false}]},
	{"question": "Qual é o maior oceano da Terra?", "isBoss": false, "answers": [ {"answer": "Oceano Pacífico", "correct": true}, {"answer": "Oceano Atlântico", "correct": false}, {"answer": "Oceano Índico", "correct": false}, {"answer": "Oceano Antártico", "correct": false}]},
	{"question": "O que é uma rocha sedimentar?", "isBoss": false, "answers": [ {"answer": "Formada pela compactação de sedimentos", "correct": true}, {"answer": "Formada por magma", "correct": false}, {"answer": "Formada por gases", "correct": false}, {"answer": "Formada por água", "correct": false}]},
	{"question": "O que é a Camada de Ozônio?", "isBoss": false, "answers": [ {"answer": "Camada que protege a Terra da radiação UV", "correct": true}, {"answer": "Camada de água da Terra", "correct": false}, {"answer": "Parte do solo fértil", "correct": false}, {"answer": "Camada de nuvens altas", "correct": false}]},
	{"question": "Quem inventou a lâmpada?", "isBoss": true, "answers": [ {"answer": "Thomas Edison", "correct": true}, {"answer": "Alexander Graham Bell", "correct": false}, {"answer": "Nikola Tesla", "correct": false}, {"answer": "Benjamin Franklin", "correct": false}]},
	{"question": "Qual é a principal função dos rins?", "isBoss": false, "answers": [ {"answer": "Filtrar o sangue", "correct": true}, {"answer": "Bombear sangue", "correct": false}, {"answer": "Produzir hormônios", "correct": false}, {"answer": "Controlar respiração", "correct": false}]},
	{"question": "O que são placas tectônicas?", "isBoss": false, "answers": [ {"answer": "Grandes blocos que formam a crosta terrestre", "correct": true}, {"answer": "Partes do oceano", "correct": false}, {"answer": "Camadas de nuvens", "correct": false}, {"answer": "Tipos de rochas", "correct": false}]},
	{"question": "Qual é o processo de transformação da lagarta em borboleta?", "isBoss": false, "answers": [ {"answer": "Metamorfose", "correct": true}, {"answer": "Fotossíntese", "correct": false}, {"answer": "Respiração", "correct": false}, {"answer": "Erosão", "correct": false}]},
	{"question": "O que é o efeito estufa?", "isBoss": true, "answers": [ {"answer": "Aquecimento da Terra por gases na atmosfera", "correct": true}, {"answer": "Resfriamento da Terra", "correct": false}, {"answer": "Chuva ácida", "correct": false}, {"answer": "Vento forte", "correct": false}]},
	{"question": "Qual é o planeta mais próximo do Sol?", "isBoss": false, "answers": [ {"answer": "Mercúrio", "correct": true}, {"answer": "Vênus", "correct": false}, {"answer": "Terra", "correct": false}, {"answer": "Marte", "correct": false}]},
	{"question": "O que são fósseis?", "isBoss": false, "answers": [ {"answer": "Restos de seres vivos preservados", "correct": true}, {"answer": "Plantas vivas", "correct": false}, {"answer": "Pedras comuns", "correct": false}, {"answer": "Insetos atuais", "correct": false}]},
	{"question": "Qual é a função do esqueleto humano?", "isBoss": false, "answers": [ {"answer": "Sustentar o corpo e proteger órgãos", "correct": true}, {"answer": "Bombear sangue", "correct": false}, {"answer": "Produzir hormônios", "correct": false}, {"answer": "Controlar respiração", "correct": false}]}
]
var logicQuestions := [
	{"question": "Qual número completa a sequência: 2, 4, 6, 8, ?", "isBoss": false, "answers": [ {"answer": "10", "correct": true}, {"answer": "12", "correct": false}, {"answer": "9", "correct": false}, {"answer": "11", "correct": false}]},
	{"question": "Se todos os gatos são animais e todos os animais respiram, então todos os gatos respiram. Isso é:", "isBoss": false, "answers": [ {"answer": "Verdadeiro", "correct": true}, {"answer": "Falso", "correct": false}, {"answer": "Não sei", "correct": false}, {"answer": "Depende", "correct": false}]},
	{"question": "Qual palavra não pertence ao grupo: 'cachorro, gato, carro, coelho'?", "isBoss": false, "answers": [ {"answer": "Carro", "correct": true}, {"answer": "Gato", "correct": false}, {"answer": "Cachorro", "correct": false}, {"answer": "Coelho", "correct": false}]},
	{"question": "Qual número falta na sequência: 1, 4, 9, 16, ?", "isBoss": false, "answers": [ {"answer": "25", "correct": true}, {"answer": "20", "correct": false}, {"answer": "30", "correct": false}, {"answer": "24", "correct": false}]},
	{"question": "Se Pedro é mais alto que João e João é mais alto que Maria, quem é o mais baixo?", "isBoss": false, "answers": [ {"answer": "Maria", "correct": true}, {"answer": "João", "correct": false}, {"answer": "Pedro", "correct": false}, {"answer": "Não dá para saber", "correct": false}]},
	{"question": "Qual figura completa o padrão: quadrado, círculo, quadrado, ?", "isBoss": true, "answers": [ {"answer": "Círculo", "correct": true}, {"answer": "Triângulo", "correct": false}, {"answer": "Quadrado", "correct": false}, {"answer": "Retângulo", "correct": false}]},
	{"question": "Se 3 + x = 7, qual é o valor de x?", "isBoss": false, "answers": [ {"answer": "4", "correct": true}, {"answer": "5", "correct": false}, {"answer": "3", "correct": false}, {"answer": "7", "correct": false}]},
	{"question": "Qual é a metade de 100?", "isBoss": false, "answers": [ {"answer": "50", "correct": true}, {"answer": "25", "correct": false}, {"answer": "100", "correct": false}, {"answer": "75", "correct": false}]},
	{"question": "Qual número completa a sequência: 5, 10, 15, 20, ?", "isBoss": false, "answers": [ {"answer": "25", "correct": true}, {"answer": "30", "correct": false}, {"answer": "24", "correct": false}, {"answer": "20", "correct": false}]},
	{"question": "Se A é irmão de B e B é irmão de C, então A é irmão de C?", "isBoss": false, "answers": [ {"answer": "Sim", "correct": true}, {"answer": "Não", "correct": false}, {"answer": "Não necessariamente", "correct": false}, {"answer": "Depende", "correct": false}]},
	{"question": "Qual número completa a sequência: 2, 4, 8, 16, ?", "isBoss": true, "answers": [ {"answer": "32", "correct": true}, {"answer": "30", "correct": false}, {"answer": "24", "correct": false}, {"answer": "34", "correct": false}]},
	{"question": "Qual figura é diferente das outras: círculo, triângulo, quadrado, bola?", "isBoss": false, "answers": [ {"answer": "Bola", "correct": true}, {"answer": "Círculo", "correct": false}, {"answer": "Triângulo", "correct": false}, {"answer": "Quadrado", "correct": false}]},
	{"question": "Se hoje é terça-feira, que dia será daqui a 5 dias?", "isBoss": false, "answers": [ {"answer": "Domingo", "correct": true}, {"answer": "Sábado", "correct": false}, {"answer": "Sexta-feira", "correct": false}, {"answer": "Segunda-feira", "correct": false}]},
	{"question": "Quantos lados tem um hexágono?", "isBoss": false, "answers": [ {"answer": "6", "correct": true}, {"answer": "5", "correct": false}, {"answer": "8", "correct": false}, {"answer": "4", "correct": false}]},
	{"question": "Qual número falta na sequência: 10, 20, 30, ?, 50", "isBoss": false, "answers": [ {"answer": "40", "correct": true}, {"answer": "35", "correct": false}, {"answer": "45", "correct": false}, {"answer": "50", "correct": false}]},
	{"question": "Qual é o próximo número na sequência: 1, 1, 2, 3, 5, ?", "isBoss": true, "answers": [ {"answer": "8", "correct": true}, {"answer": "7", "correct": false}, {"answer": "6", "correct": false}, {"answer": "10", "correct": false}]},
	{"question": "Se João tem 5 maçãs e come 2, quantas restam?", "isBoss": false, "answers": [ {"answer": "3", "correct": true}, {"answer": "2", "correct": false}, {"answer": "4", "correct": false}, {"answer": "5", "correct": false}]},
	{"question": "Qual número completa a sequência: 1, 2, 4, 7, 11, ?", "isBoss": false, "answers": [ {"answer": "16", "correct": true}, {"answer": "15", "correct": false}, {"answer": "17", "correct": false}, {"answer": "14", "correct": false}]},
	{"question": "Qual palavra não pertence ao grupo: maçã, banana, laranja, carro?", "isBoss": false, "answers": [ {"answer": "Carro", "correct": true}, {"answer": "Banana", "correct": false}, {"answer": "Maçã", "correct": false}, {"answer": "Laranja", "correct": false}]},
	{"question": "Qual é o número que falta: 3, 6, 9, ?, 15", "isBoss": true, "answers": [ {"answer": "12", "correct": true}, {"answer": "11", "correct": false}, {"answer": "13", "correct": false}, {"answer": "10", "correct": false}]},
	{"question": "Se todos os peixes vivem na água e Nemo é um peixe, Nemo vive na água?", "isBoss": false, "answers": [ {"answer": "Sim", "correct": true}, {"answer": "Não", "correct": false}, {"answer": "Não necessariamente", "correct": false}, {"answer": "Depende", "correct": false}]},
	{"question": "Qual figura completa a sequência: △, □, △, □, ?", "isBoss": false, "answers": [ {"answer": "△", "correct": true}, {"answer": "□", "correct": false}, {"answer": "○", "correct": false}, {"answer": "◇", "correct": false}]},
	{"question": "Qual é o próximo número na sequência: 5, 10, 20, 40, ?", "isBoss": false, "answers": [ {"answer": "80", "correct": true}, {"answer": "70", "correct": false}, {"answer": "60", "correct": false}, {"answer": "90", "correct": false}]},
	{"question": "Qual número é o dobro de 12?", "isBoss": false, "answers": [ {"answer": "24", "correct": true}, {"answer": "22", "correct": false}, {"answer": "26", "correct": false}, {"answer": "20", "correct": false}]},
	{"question": "Se 7 + ? = 12, qual é o número que falta?", "isBoss": false, "answers": [ {"answer": "5", "correct": true}, {"answer": "4", "correct": false}, {"answer": "6", "correct": false}, {"answer": "7", "correct": false}]},
	{"question": "Qual número completa a sequência: 100, 90, 80, ?, 60", "isBoss": true, "answers": [ {"answer": "70", "correct": true}, {"answer": "75", "correct": false}, {"answer": "65", "correct": false}, {"answer": "80", "correct": false}]},
	{"question": "Qual número vem depois de 19, 21, 23, ?", "isBoss": false, "answers": [ {"answer": "25", "correct": true}, {"answer": "24", "correct": false}, {"answer": "26", "correct": false}, {"answer": "27", "correct": false}]},
	{"question": "Se hoje é sábado, que dia será daqui a 3 dias?", "isBoss": false, "answers": [ {"answer": "Terça-feira", "correct": true}, {"answer": "Segunda-feira", "correct": false}, {"answer": "Domingo", "correct": false}, {"answer": "Quarta-feira", "correct": false}]},
	{"question": "Qual figura é diferente: círculo, triângulo, quadrado, triângulo invertido?", "isBoss": false, "answers": [ {"answer": "Círculo", "correct": true}, {"answer": "Triângulo", "correct": false}, {"answer": "Quadrado", "correct": false}, {"answer": "Triângulo invertido", "correct": false}]},
	{"question": "Qual número completa a sequência: 1, 3, 6, 10, ?", "isBoss": true, "answers": [ {"answer": "15", "correct": true}, {"answer": "14", "correct": false}, {"answer": "16", "correct": false}, {"answer": "12", "correct": false}]},
	{"question": "Se uma caneta custa 2 reais, quanto custam 5 canetas?", "isBoss": false, "answers": [ {"answer": "10 reais", "correct": true}, {"answer": "8 reais", "correct": false}, {"answer": "12 reais", "correct": false}, {"answer": "5 reais", "correct": false}]},
	{"question": "Qual número completa a sequência: 2, 6, 12, 20, ?", "isBoss": false, "answers": [ {"answer": "30", "correct": true}, {"answer": "28", "correct": false}, {"answer": "32", "correct": false}, {"answer": "24", "correct": false}]},
	{"question": "Se Ana tem 3 irmãs e cada irmã tem 2 brinquedos, quantos brinquedos no total?", "isBoss": false, "answers": [ {"answer": "6", "correct": true}, {"answer": "5", "correct": false}, {"answer": "3", "correct": false}, {"answer": "9", "correct": false}]},
	{"question": "Qual número completa a sequência: 1, 2, 4, 8, 16, ?", "isBoss": true, "answers": [ {"answer": "32", "correct": true}, {"answer": "30", "correct": false}, {"answer": "28", "correct": false}, {"answer": "24", "correct": false}]},
	{"question": "Se todos os pássaros têm asas e o pardal é um pássaro, o pardal tem asas?", "isBoss": false, "answers": [ {"answer": "Sim", "correct": true}, {"answer": "Não", "correct": false}, {"answer": "Não necessariamente", "correct": false}, {"answer": "Depende", "correct": false}]},
	{"question": "Qual figura completa o padrão: △, □, △, □, △, ?", "isBoss": false, "answers": [ {"answer": "□", "correct": true}, {"answer": "△", "correct": false}, {"answer": "○", "correct": false}, {"answer": "◇", "correct": false}]},
	{"question": "Qual número vem a seguir: 50, 45, 40, ?", "isBoss": false, "answers": [ {"answer": "35", "correct": true}, {"answer": "30", "correct": false}, {"answer": "36", "correct": false}, {"answer": "34", "correct": false}]},
	{"question": "Se dois lápis custam 4 reais, quanto custa 1 lápis?", "isBoss": false, "answers": [ {"answer": "2 reais", "correct": true}, {"answer": "3 reais", "correct": false}, {"answer": "4 reais", "correct": false}, {"answer": "1 real", "correct": false}]},
	{"question": "Qual número completa a sequência: 3, 6, 12, 24, ?", "isBoss": true, "answers": [ {"answer": "48", "correct": true}, {"answer": "50", "correct": false}, {"answer": "46", "correct": false}, {"answer": "36", "correct": false}]},
	{"question": "Qual número completa a sequência: 1, 2, 3, 5, 8, ?", "isBoss": false, "answers": [ {"answer": "13", "correct": true}, {"answer": "12", "correct": false}, {"answer": "11", "correct": false}, {"answer": "10", "correct": false}]},
	{"question": "Se todos os carros têm rodas e um Fusca é um carro, o Fusca tem rodas?", "isBoss": false, "answers": [ {"answer": "Sim", "correct": true}, {"answer": "Não", "correct": false}, {"answer": "Não necessariamente", "correct": false}, {"answer": "Depende", "correct": false}]}
]
var map1Questions := mathQuestions
var map2Questions := cienceQuestions
var map3Questions := portugueseQuestions
var map4Questions := logicQuestions

func getQuestionsForCurrentMap() -> Array:
	match currentMap:
		GameEnums.MapEnum.MAP1:
			return map1Questions
		GameEnums.MapEnum.MAP2:
			return map2Questions
		GameEnums.MapEnum.MAP3:
			return map3Questions
		GameEnums.MapEnum.MAP4:
			return map4Questions
		_:
			return []
